steps:
  - label: ":maven: Build and Deploy"
    command:
      - export SONAR_TOKEN=$(buildkite-agent secret get SONAR_TOKEN)
      - mvn -Dgpg.skip=true clean deploy sonar:sonar -Psnapshot
    secrets:
      BUILDKITE_ANALYTICS_TOKEN: "SchemasBuildkiteAnalytics"
    agents:
      queue: "java_build_queue_aws"